"use client";

import styles from "./MainAnimation.module.css";

const elements = [
  { className: "bg", count: 34 },
  { className: "hair-light", count: 4 },
  { className: "bg", count: 17 },
  { className: "hair-light", count: 1 },
  { className: "hair", count: 5 },
  { className: "hair-light", count: 3 },
  { className: "bg", count: 14 },
  { className: "hair-light", count: 1 },
  { className: "hair", count: 8 },
  { className: "hair-light", count: 2 },
  { className: "bg", count: 12 },
  { className: "hair-light", count: 1 },
  { className: "hair", count: 11 },
  { className: "hair-light", count: 1 },
  { className: "bg", count: 10 },
  { className: "hair", count: 13 },
  { className: "hair-light", count: 2 },
  { className: "bg", count: 8 },
  { className: "hair", count: 5 },
  { className: "hair-dark", count: 1 },
  { className: "hair", count: 2 },
  { className: "hair-dark", count: 1 },
  { className: "face", count: 2 },
  { className: "hair", count: 4 },
  { className: "hair-light", count: 1 },
  { className: "bg", count: 8 },
  { className: "hair", count: 4 },
  { className: "hair-dark", count: 1 },
  { className: "hair", count: 2 },
  { className: "hair-dark", count: 1 },
  { className: "face", count: 4 },
  { className: "hair-dark", count: 1 },
  { className: "hair", count: 3 },
  { className: "hair-light", count: 1 },
  { className: "bg", count: 7 },
  { className: "hair", count: 3 },
  { className: "hair-dark", count: 4 },
  { className: "face", count: 5 },
  { className: "hair-dark", count: 3 },
  { className: "hair", count: 1 },
  { className: "hair-light", count: 1 },
  { className: "bg", count: 6 },
  { className: "hair", count: 3 },
  { className: "hair-dark", count: 2 },
  { className: "face", count: 11 },
  { className: "hair-dark", count: 1 },
  { className: "hair", count: 1 },
  { className: "hair-light", count: 1 },
  { className: "bg", count: 5 },
  { className: "hair", count: 2 },
  { className: "hair-dark", count: 2 },
  { className: "face", count: 2 },
  { className: "glasses", count: 3 },
  { className: "face", count: 3 },
  { className: "glasses", count: 3 },
  { className: "face", count: 1 },
  { className: "hair-dark", count: 1 },
  { className: "hair", count: 1 },
  { className: "hair-light", count: 1 },
  { className: "bg", count: 5 },
  { className: "hair", count: 2 },
  { className: "hair-dark", count: 2 },
  { className: "face", count: 1 },
  { className: "glasses", count: 1 },
  { className: "face glass", count: 3 },
  { className: "glasses", count: 1 },
  { className: "face", count: 1 },
  { className: "glasses", count: 1 },
  { className: "face glass", count: 3 },
  { className: "glasses", count: 1 },
  { className: "hair-dark", count: 1 },
  { className: "hair", count: 1 },
  { className: "hair-light", count: 1 },
  { className: "bg", count: 5 },
  { className: "hair", count: 2 },
  { className: "face", count: 1 },
  { className: "hair-dark", count: 1 },
  { className: "glasses", count: 2 },
  { className: "face glass", count: 1 },
  { className: "eye glass", count: 1 },
  { className: "face glass", count: 1 },
  { className: "glasses", count: 3 },
  { className: "face glass", count: 1 },
  { className: "eye glass", count: 1 },
  { className: "face glass", count: 1 },
  { className: "glasses", count: 2 },
  { className: "hair", count: 1 },
  { className: "hair-light", count: 1 },
  { className: "bg", count: 6 },
  { className: "hair", count: 1 },
  { className: "face", count: 3 },
  { className: "glasses", count: 1 },
  { className: "face glass", count: 3 },
  { className: "glasses", count: 1 },
  { className: "face", count: 1 },
  { className: "glasses", count: 1 },
  { className: "face glass", count: 3 },
  { className: "glasses", count: 1 },
  { className: "hair", count: 2 },
  { className: "bg", count: 7 },
  { className: "hair", count: 2 },
  { className: "face-dark", count: 1 },
  { className: "face", count: 2 },
  { className: "glasses", count: 3 },
  { className: "face", count: 1 },
  { className: "face-dark", count: 1 },
  { className: "face", count: 1 },
  { className: "glasses", count: 3 },
  { className: "face", count: 1 },
  { className: "hair", count: 1 },
  { className: "bg", count: 10 },
  { className: "hair", count: 1 },
  { className: "hair-dark", count: 1 },
  { className: "face", count: 3 },
  { className: "lip", count: 1 },
  { className: "face", count: 3 },
  { className: "lip", count: 1 },
  { className: "face", count: 3 },
  { className: "hair", count: 1 },
  { className: "bg", count: 11 },
  { className: "hair", count: 1 },
  { className: "hair-dark", count: 1 },
  { className: "face", count: 3 },
  { className: "lip", count: 3 },
  { className: "face", count: 3 },
  { className: "hair-dark", count: 1 },
  { className: "bg", count: 15 },
  { className: "face", count: 7 },
  { className: "bg", count: 17 },
  { className: "face-dark", count: 2 },
  { className: "face", count: 4 },
  { className: "bg", count: 15 },
  { className: "shirts", count: 2 },
  { className: "shirts-dark", count: 1 },
  { className: "face", count: 1 },
  { className: "face-dark", count: 5 },
  { className: "shirts-dark", count: 1 },
  { className: "shirts", count: 2 },
  { className: "bg", count: 11 },
  { className: "shirts", count: 4 },
  { className: "shirts-dark", count: 1 },
  { className: "face", count: 1 },
  { className: "face-dark", count: 3 },
  { className: "shirts-dark", count: 1 },
  { className: "shirts", count: 4 },
  { className: "bg", count: 9 },
  { className: "shirts", count: 2 },
  { className: "shirts-dark", count: 2 },
  { className: "shirts", count: 1 },
  { className: "shirts-dark", count: 2 },
  { className: "face", count: 2 },
  { className: "shirts-dark", count: 1 },
  { className: "shirts", count: 2 },
  { className: "shirts-dark", count: 3 },
  { className: "shirts", count: 1 },
  { className: "bg", count: 7 },
  { className: "shirts", count: 1 },
  { className: "shirts-dark", count: 5 },
  { className: "shirts", count: 2 },
  { className: "shirts-dark", count: 2 },
  { className: "shirts", count: 2 },
  { className: "shirts-dark", count: 5 },
  { className: "bg", count: 7 },
  { className: "shirts-dark", count: 7 },
  { className: "shirts", count: 4 },
  { className: "shirts-dark", count: 6 },
  { className: "shirts", count: 1 },
  { className: "bg", count: 3 },
];
export default function MainAnimation(props: { showStatic: boolean }) {
  const { showStatic } = props;

  const classes = (className: string) =>
    className
      .split(" ")
      .map((c) => styles[c])
      .join(" ");

  const style = showStatic
    ? {
        animation: "none",
        backgroundColor: `var(--bgc-after)` as string,
        transform: "translateY(0) translateX(0) scale(1)",
      }
    : undefined;

  return (
    <section
      className={`${styles.animation} ${showStatic ? styles["animation-done"] : ""}`}
    >
      {elements.map(({ className, count }, i) =>
        Array.from({ length: count }, (_, j) => (
          <div
            key={`${className}-${i}-${j}`}
            className={classes(className)}
            style={style}
          />
        )),
      )}
    </section>
  );
}
